// 前端技术栈网站数据
// 分类：Framework | Library | Tool | Design | Learning
export const TECH_STACK_ITEMS = [
  // === Framework 框架 ===
  { name: 'React', description: 'A JavaScript library for building user interfaces', icon: '⚛️', url: 'https://react.dev', category: 'Framework' },
  { name: 'Next.js', description: 'The React Framework for production', icon: '▲', url: 'https://nextjs.org', category: 'Framework' },
  { name: 'Vue.js', description: 'The Progressive JavaScript Framework', icon: '💚', url: 'https://vuejs.org', category: 'Framework' },
  { name: 'Nuxt', description: 'The Intuitive Vue Framework', icon: '💚', url: 'https://nuxt.com', category: 'Framework' },
  { name: 'Angular', description: 'Platform for building web applications', icon: '🅰️', url: 'https://angular.dev', category: 'Framework' },
  { name: 'Svelte', description: 'Cybernetically enhanced web apps', icon: '🔥', url: 'https://svelte.dev', category: 'Framework' },
  { name: 'SvelteKit', description: 'The fastest way to build Svelte apps', icon: '🔥', url: 'https://kit.svelte.dev', category: 'Framework' },
  { name: 'Solid', description: 'Simple and performant reactivity', icon: '💎', url: 'https://www.solidjs.com', category: 'Framework' },
  { name: 'Remix', description: 'Full stack web framework', icon: '💿', url: 'https://remix.run', category: 'Framework' },
  { name: 'Astro', description: 'The web framework for content-driven websites', icon: '🚀', url: 'https://astro.build', category: 'Framework' },
  { name: 'Qwik', description: 'The HTML-first framework', icon: '⚡', url: 'https://qwik.builder.io', category: 'Framework' },
  { name: 'Preact', description: 'Fast 3kB alternative to React', icon: '⚛️', url: 'https://preactjs.com', category: 'Framework' },
  { name: 'Gatsby', description: 'The best React-based framework', icon: '🎨', url: 'https://www.gatsbyjs.com', category: 'Framework' },
  { name: 'Ember.js', description: 'A framework for ambitious web developers', icon: '🐹', url: 'https://emberjs.com', category: 'Framework' },

  // === Library 组件库 ===
  { name: 'Ant Design', description: '企业级UI设计语言和React组件库', icon: '🐜', url: 'https://ant.design', category: 'Library' },
  { name: 'Ant Design Vue', description: 'Ant Design的Vue实现', icon: '🐜', url: 'https://antdv.com', category: 'Library' },
  { name: 'Element Plus', description: '基于Vue 3的组件库', icon: '🎨', url: 'https://element-plus.org', category: 'Library' },
  { name: 'Arco Design', description: '字节跳动企业级设计系统', icon: '🎯', url: 'https://arco.design', category: 'Library' },
  { name: 'Semi Design', description: '抖音企业级设计系统', icon: '🎵', url: 'https://semi.design', category: 'Library' },
  { name: 'TDesign', description: '腾讯企业级设计体系', icon: '🎨', url: 'https://tdesign.tencent.com', category: 'Library' },
  { name: 'Naive UI', description: 'Vue 3 组件库，使用TypeScript', icon: '🌈', url: 'https://www.naiveui.com', category: 'Library' },
  { name: 'Vant', description: '轻量、可靠的移动端组件库', icon: '📱', url: 'https://vant-ui.github.io', category: 'Library' },
  { name: 'NutUI', description: '京东风格的移动端组件库', icon: '🥜', url: 'https://nutui.jd.com', category: 'Library' },
  { name: 'Varlet', description: 'Material风格移动端组件库', icon: '🎨', url: 'https://varlet.pages.dev', category: 'Library' },
  { name: 'Material-UI', description: 'React UI library based on Material Design', icon: '🎨', url: 'https://mui.com', category: 'Library' },
  { name: 'Chakra UI', description: 'Simple, modular and accessible component library', icon: '⚡', url: 'https://chakra-ui.com', category: 'Library' },
  { name: 'Mantine', description: 'React components library with native dark theme', icon: '🎨', url: 'https://mantine.dev', category: 'Library' },
  { name: 'Radix UI', description: 'Unstyled, accessible components', icon: '🧩', url: 'https://www.radix-ui.com', category: 'Library' },
  { name: 'Shadcn/ui', description: 'Beautiful components with Radix UI and Tailwind', icon: '🌓', url: 'https://ui.shadcn.com', category: 'Library' },
  { name: 'Headless UI', description: 'Unstyled, accessible UI components', icon: '🎯', url: 'https://headlessui.com', category: 'Library' },
  { name: 'DaisyUI', description: 'The most popular component library for Tailwind CSS', icon: '🌼', url: 'https://daisyui.com', category: 'Library' },
  { name: 'PrimeReact', description: 'Rich set of open source UI components', icon: '🎨', url: 'https://primereact.org', category: 'Library' },
  { name: 'Vuetify', description: 'Material Component Framework for Vue.js', icon: '💎', url: 'https://vuetifyjs.com', category: 'Library' },
  { name: 'Quasar', description: 'Build high-performance VueJS user interfaces', icon: '🌟', url: 'https://quasar.dev', category: 'Library' },
  { name: 'NG-ZORRO', description: 'Ant Design for Angular', icon: '🐜', url: 'https://ng.ant.design', category: 'Library' },
  { name: 'PrimeNG', description: 'Rich UI components for Angular', icon: '🎨', url: 'https://primeng.org', category: 'Library' },
  { name: 'DevUI', description: '华为企业级前端组件库', icon: '🎨', url: 'https://devui.design', category: 'Library' },
  { name: 'iView', description: '基于Vue.js的企业级UI组件库', icon: '🎨', url: 'https://iviewui.com', category: 'Library' },

  // === Tool 工具 ===
  { name: 'TypeScript', description: 'JavaScript with syntax for types', icon: '📘', url: 'https://www.typescriptlang.org', category: 'Tool' },
  { name: 'Vite', description: 'Next Generation Frontend Tooling', icon: '⚡', url: 'https://vitejs.dev', category: 'Tool' },
  { name: 'Webpack', description: 'A static module bundler', icon: '📦', url: 'https://webpack.js.org', category: 'Tool' },
  { name: 'Rollup', description: 'Module bundler for JavaScript', icon: '📦', url: 'https://rollupjs.org', category: 'Tool' },
  { name: 'Turbopack', description: 'Incremental bundler optimized for JavaScript', icon: '⚡', url: 'https://turbo.build/pack', category: 'Tool' },
  { name: 'ESLint', description: 'Find and fix problems in JavaScript code', icon: '🔍', url: 'https://eslint.org', category: 'Tool' },
  { name: 'Prettier', description: 'Opinionated code formatter', icon: '✨', url: 'https://prettier.io', category: 'Tool' },
  { name: 'Babel', description: 'The compiler for next generation JavaScript', icon: '🔄', url: 'https://babeljs.io', category: 'Tool' },
  { name: 'PostCSS', description: 'A tool for transforming CSS with JavaScript', icon: '🎨', url: 'https://postcss.org', category: 'Tool' },
  { name: 'Tailwind CSS', description: 'Utility-first CSS framework', icon: '🎨', url: 'https://tailwindcss.com', category: 'Tool' },
  { name: 'UnoCSS', description: 'Instant On-demand Atomic CSS Engine', icon: '⚡', url: 'https://unocss.dev', category: 'Tool' },
  { name: 'Sass', description: 'CSS with superpowers', icon: '🎨', url: 'https://sass-lang.com', category: 'Tool' },
  { name: 'Less', description: 'It\'s CSS, with just a little more', icon: '🎨', url: 'https://lesscss.org', category: 'Tool' },
  { name: 'Vitest', description: 'Next Generation Testing Framework', icon: '🧪', url: 'https://vitest.dev', category: 'Tool' },
  { name: 'Jest', description: 'Delightful JavaScript Testing', icon: '🃏', url: 'https://jestjs.io', category: 'Tool' },
  { name: 'Cypress', description: 'Fast, easy and reliable testing', icon: '🌲', url: 'https://www.cypress.io', category: 'Tool' },
  { name: 'Playwright', description: 'Reliable end-to-end testing', icon: '🎭', url: 'https://playwright.dev', category: 'Tool' },
  { name: 'Storybook', description: 'Build component driven UIs', icon: '📚', url: 'https://storybook.js.org', category: 'Tool' },
  { name: 'Nx', description: 'Smart Monorepos, Fast CI', icon: '🔷', url: 'https://nx.dev', category: 'Tool' },
  { name: 'Turborepo', description: 'High-performance build system', icon: '⚡', url: 'https://turbo.build/repo', category: 'Tool' },
  { name: 'pnpm', description: 'Fast, disk space efficient package manager', icon: '📦', url: 'https://pnpm.io', category: 'Tool' },
  { name: 'npm', description: 'Package manager for JavaScript', icon: '📦', url: 'https://www.npmjs.com', category: 'Tool' },
  { name: 'Yarn', description: 'Fast, reliable, and secure dependency management', icon: '📦', url: 'https://yarnpkg.com', category: 'Tool' },
  { name: 'Vercel', description: 'Platform for frontend developers', icon: '▲', url: 'https://vercel.com', category: 'Tool' },
  { name: 'Netlify', description: 'The fastest way to build websites', icon: '🌐', url: 'https://www.netlify.com', category: 'Tool' },
  { name: 'Cloudflare', description: 'The Web Performance & Security Company', icon: '☁️', url: 'https://www.cloudflare.com', category: 'Tool' },
  { name: 'GitHub', description: 'Where the world builds software', icon: '🐙', url: 'https://github.com', category: 'Tool' },
  { name: 'GitLab', description: 'The DevOps platform', icon: '🦊', url: 'https://gitlab.com', category: 'Tool' },
  { name: 'Can I Use', description: 'Browser support tables', icon: '🌐', url: 'https://caniuse.com', category: 'Tool' },

  // === Design 设计 ===
  { name: 'Figma', description: 'Collaborative interface design tool', icon: '🎨', url: 'https://www.figma.com', category: 'Design' },
  { name: 'Sketch', description: 'Design tool for digital products', icon: '💎', url: 'https://www.sketch.com', category: 'Design' },
  { name: 'Adobe XD', description: 'Design, prototype, and share', icon: '🎨', url: 'https://www.adobe.com/products/xd.html', category: 'Design' },
  { name: 'Framer', description: 'Design tool for interactive websites', icon: '🎨', url: 'https://www.framer.com', category: 'Design' },
  { name: 'Framer Motion', description: 'Production-ready motion library for React', icon: '🎬', url: 'https://www.framer.com/motion', category: 'Design' },
  { name: 'GSAP', description: 'Professional-grade animation for the web', icon: '🎬', url: 'https://greensock.com/gsap', category: 'Design' },
  { name: 'Lottie', description: 'Lightweight, scalable animations', icon: '🎬', url: 'https://airbnb.io/lottie', category: 'Design' },
  { name: 'Animate.css', description: 'Just-add-water CSS animations', icon: '✨', url: 'https://animate.style', category: 'Design' },
  { name: 'Iconify', description: 'All popular icon sets, one framework', icon: '🎯', url: 'https://iconify.design', category: 'Design' },
  { name: 'Lucide', description: 'Beautiful & consistent icon toolkit', icon: '🎯', url: 'https://lucide.dev', category: 'Design' },
  { name: 'Heroicons', description: 'Beautiful hand-crafted SVG icons', icon: '🎯', url: 'https://heroicons.com', category: 'Design' },

  // === Learning 学习 ===
  { name: 'MDN Web Docs', description: 'Resources for developers, by developers', icon: '📚', url: 'https://developer.mozilla.org', category: 'Learning' },
  { name: 'JavaScript.info', description: 'The Modern JavaScript Tutorial', icon: '📘', url: 'https://javascript.info', category: 'Learning' },
  { name: 'CSS-Tricks', description: 'Daily articles about CSS, HTML, JavaScript', icon: '🎯', url: 'https://css-tricks.com', category: 'Learning' },
  { name: 'Web.dev', description: 'Build the web you want', icon: '🌐', url: 'https://web.dev', category: 'Learning' },
  { name: 'freeCodeCamp', description: 'Learn to code for free', icon: '🔥', url: 'https://www.freecodecamp.org', category: 'Learning' },
  { name: 'Stack Overflow', description: 'Where developers learn and share', icon: '📝', url: 'https://stackoverflow.com', category: 'Learning' }
]
